config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :questions, only: [:index, :new, :show, :create, :destroy]
  resources :users, only: [:show]
  resources :admins, only: [:show]
  resources :answers, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :playlists, only: [:index]
  resources :maps, only: [:index]
  
  # search controller
  get '/search', to: 'searchs#search'
  get '/search/form', to: 'searchs#form'
  
  # like controller
  get 'likes/:id' => 'likes#show', as: 'likes'
  post 'likes/:id' => 'likes#create', as: 'create_like'
  delete 'likes/:id' => 'likes#destroy', as: 'destroy_like'
  
  root 'top#index'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :answers
  has_one_attached :avatar
  
  # update_without_current_password
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  # association
  belongs_to :question
  belongs_to :admin
  
  # validation
  validates :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :text, maximum: 200, allow_nil: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  # association
  belongs_to :question
  belongs_to :user
  
end

app/models/question.rb
class Question < ApplicationRecord

  # association
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_one :answer, dependent: :destroy
  
  # validation
  validates :title, :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :title, maximum: 20, allow_nil: true
  validates_length_of :text, maximum: 100, allow_nil: true
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :questions
  has_many :likes
  has_one_attached :avatar
  
  #like
  def liked_by?(question_id)
    likes.where(question_id: question_id).exists?
  end
         
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def show
    @admin = Admin.find(params[:id])
  end
  
  protected
  def after_sign_in_path_for(resource)
    admin_items_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :question_params, only: [:create, :destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    Like.create(user_id: current_user.id, question_id: params[:id])
  end
  
  def destroy
    Like.find_by(user_id: current_user.id, question_id: params[:id]).destroy
  end
  
  private
  
  def question_params
    @question = Question.find(params[:id])
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
  end

  def show
    @question = Question.find(params[:id])
  end
  
  def new
    @question = Question.new
  end

  def create
    Question.create(create_params)
    redirect_to("/")
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to("/")
  end

  private
  def create_params
    params.require(:question).permit(:text, :title).merge(user_id: current_user.id)
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
  def index
    @questions = Question.all.order(created_at: :desc)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/_show.html.erb
<h1 class="box1"><%= question.title %></h1>
<p class="box2"><%= question.text %></p>
<% if question.user.avatar.attached? %>
  <%= link_to image_tag(question.user.avatar), user_path(question.user_id), class: "box3-1" %>
<% else %>
  <%= link_to image_tag("/no-profile.png"), user_path(question.user_id), class: "box3-1" %>
<% end %>
<p class="box3-2"><%= question.user.nickname %></p>
    
<!--回答済み-->
<% if question.answer %>
  <p class="box4"><%= question.answer.text %></p>
  <% if question.answer.admin.avatar.attached? %>
    <%= link_to image_tag(question.answer.admin.avatar), admin_path(question.answer.admin_id), class: "box5-1" %>
  <% else %>
    <%= link_to image_tag("/no-profile.png"), admin_path(question.answer.admin_id), class: "box5-1" %>
  <% end %>
  <p class="box5-2"><%= question.answer.admin.name %></p>
  <ul class="box6">
    <!--いいね機能-->
    <li class="box-icon">
      <% if user_signed_in? %>
        <% if current_user.liked_by?(question.id) %> 
          <%= link_to destroy_like_path(question), method: :DELETE, remote: true do %>
            <i class="fa fa-heart unlike-btn"></i>
            <%= question.likes.count %>
          <% end %>
        <% else %>
          <%= link_to create_like_path(question), method: :POST, remote: true do %> 
            <i class="fa fa-heart like-btn"></i>
            <%= question.likes.count %> 
          <% end %>
        <% end %>
      <!--回答編集-->
      <% elsif admin_signed_in? %>
        <%= link_to edit_answer_path(question.answer) do %> 
           <i class="fas fa-pen"></i>
         <% end %>
      <% end %>
    </li>
    <!--質問削除-->
    <li class="box-icon">
      <% if user_signed_in? %>
        <% if current_user.id === question.user_id %>
          <%= link_to "/questions/#{question.id}", method: :delete do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      <% elsif admin_signed_in?%>
        <%= link_to "/questions/#{question.id}", method: :delete do %>
          <i class="fas fa-trash"></i>
        <% end %>
      <% end %>
    </li>
    <!--回答削除-->
    <li class="box-icon">
      <% if admin_signed_in? %>
        <%= link_to "回答を削除", "/answers/#{question.answer.id}", method: :delete %>
      <% end %>
    </li>
  </ul>
<!--管理者 回答前-->
<% elsif admin_signed_in? %>
  <ul class="box4">
    <li class="box-icon">
      <%= link_to "回答する", new_answer_path(question_id: question.id) %>
    </li>
    <li class="box-icon">
      <%= link_to "/questions/#{question.id}", method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </li>
  </ul>
<!--ユーザー回答前-->
<% else %>  
  <ul class="box4">
    <li class="box-icon">
      <% if user_signed_in? %>
        <% if current_user.liked_by?(question.id) %> 
          <%= link_to destroy_like_path(question), method: :DELETE, remote: true do %>
            <i class="fa fa-heart unlike-btn"></i>
            <%= question.likes.count %>
          <% end %>
        <% else %>
          <%= link_to create_like_path(question), method: :POST, remote: true do %> 
            <i class="fa fa-heart like-btn"></i>
            <%= question.likes.count %> 
          <% end %>
        <% end %>
      <% end %>
    </li>
    <li class="box-icon">
      <% if user_signed_in? %>
        <% if current_user.id === question.user_id %>
          <%= link_to "/questions/#{question.id}", method: :delete do %>
             <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      <% end %>
    </li>
  </ul>
<% end %>

app/views/questions/index.html.slim
.boxes
  .opc-description
    .opc-description-text
      h1.title
        |  Opc(Online Psychiatric Consultation)は
        br
        |  中学時代大きな挫折体験をした大学生の私が
        br
        |  心療相談に答えるアプリです。
        br
        br
        |  当時の自分が心療内科になんか通いたくないと思った経験から開発しました。
        br
        br
        |  オンラインで気軽に質問できる場と
        br
        |  Spotifyとの連携で音楽の提案を提供することで
        br
        |  ユーザーの方々が心療内科に通うきっかけや
        br
        |  手助けになれればと思います。 
    .opc-description-profile
      = image_tag "/profile-image.jpg", alt: "画像がありません", style: "width: 100%"
      h1
        | FURUYA YUUKI
      h1

app/views/questions/new.html.slim
.boxes
  .question-background
    h1
      | 質問する
    = form_with model: @question do |f|
      = f.text_area :title, placeholder: "例：生活リズムについて(20文字以内)", size: "33x1", maxlength: "20"
      br
      = f.text_area :text, placeholder: "例：生活リズムを治すにはどうしたらいいですか？(100文字以内)", size: "33x5", maxlength: "100"
      br
      = f.submit "質問する"

app/views/questions/show.html.slim
.boxes
  |  <div class="big-box" id="question_
  = @question.id
  | "> 
  = render 'show', question: @question