config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :questions, only: [:index, :new, :show, :create, :destroy]
  resources :users, only: [:show]
  resources :admins, only: [:show]
  resources :answers, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :playlists, only: [:index]
  resources :maps, only: [:index]
  
  # search controller
  get '/search', to: 'searchs#search'
  get '/search/form', to: 'searchs#form'
  
  # like controller
  get 'likes/:id' => 'likes#show', as: 'likes'
  post 'likes/:id' => 'likes#create', as: 'create_like'
  delete 'likes/:id' => 'likes#destroy', as: 'destroy_like'
  
  root 'top#index'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :answers
  has_one_attached :avatar
  
  # update_without_current_password
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  # association
  belongs_to :question
  belongs_to :admin
  
  # validation
  validates :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :text, maximum: 200, allow_nil: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  # association
  belongs_to :question
  belongs_to :user
  
end

app/models/question.rb
class Question < ApplicationRecord

  # association
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_one :answer, dependent: :destroy
  
  # validation
  validates :title, :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :title, maximum: 20, allow_nil: true
  validates_length_of :text, maximum: 100, allow_nil: true
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :questions
  has_many :likes
  has_one_attached :avatar
  
  #like
  def liked_by?(question_id)
    likes.where(question_id: question_id).exists?
  end
         
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def show
    @admin = Admin.find(params[:id])
  end
  
  protected
  def after_sign_in_path_for(resource)
    admin_items_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end
  
  def show
    @answer = Answer.find(params[:id])
  end

  def create
    Answer.create(create_params)
    redirect_to("/")
  end
  
  def edit
    @answer = Answer.find(params[:id])
  end
  
  def update
    answer = Answer.find(params[:id])
    answer.update(update_params)
    redirect_to("/")
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    redirect_to("/")
  end

  private
  def create_params
    params.require(:answer).permit(:question_id, :text).merge(admin_id: current_admin.id)
  end
  
  def update_params
    params.require(:answer).permit(:text)
  end  
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :question_params, only: [:create, :destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    Like.create(user_id: current_user.id, question_id: params[:id])
  end
  
  def destroy
    Like.find_by(user_id: current_user.id, question_id: params[:id]).destroy
  end
  
  private
  
  def question_params
    @question = Question.find(params[:id])
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
  def index
    @questions = Question.all.order(created_at: :desc)
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]
  
  def create
    super
    WelcomeMailer.with(user: @user).welcome_email.deliver_later
  end

  private
  
  def update_resource(resource, params)
    resource.update_without_password(params)
    root_path
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_account_update_params, only: [:update]

  private
  
  def update_resource(resource, params)
    resource.update_without_password(params)
    root_path
  end
  
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name), style: "line-height: 20px" %><br />
<% end %>

<!--<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />-->
<!--<% end %>-->

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.slim
.boxes
  .box
    h1.box1
      = @user.nickname
    - if @user.avatar.attached?
      = image_tag @user.avatar, class: "box2"
    - else
      = image_tag ("/no-profile.png"), class: "box2"
    = link_to "投稿", user_path(@user.id), class: "box3-1"
    = link_to "いいね", likes_path(@user.id), class: "box3-2"
    - if current_user || current_admin === @user
      = link_to "プロフィール編集", edit_user_registration_path, class: "box4"
      
  - @user.questions.order(created_at: :desc).each do |question|
    |  <div class="box" id="question_
    = question.id
    | "> 
    = render 'top/top', question: question