config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :questions, only: [:index, :new, :show, :create, :destroy]
  resources :users, only: [:show]
  resources :admins, only: [:show]
  resources :answers, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :playlists, only: [:index]
  resources :maps, only: [:index]
  
  # search controller
  get '/search', to: 'searchs#search'
  get '/search/form', to: 'searchs#form'
  
  # like controller
  get 'likes/:id' => 'likes#show', as: 'likes'
  post 'likes/:id' => 'likes#create', as: 'create_like'
  delete 'likes/:id' => 'likes#destroy', as: 'destroy_like'
  
  root 'top#index'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :answers
  has_one_attached :avatar
  
  # update_without_current_password
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  # association
  belongs_to :question
  belongs_to :admin
  
  # validation
  validates :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :text, maximum: 200, allow_nil: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  # association
  belongs_to :question
  belongs_to :user
  
end

app/models/question.rb
class Question < ApplicationRecord

  # association
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_one :answer, dependent: :destroy
  
  # validation
  validates :title, :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :title, maximum: 20, allow_nil: true
  validates_length_of :text, maximum: 100, allow_nil: true
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :questions
  has_many :likes
  has_one_attached :avatar
  
  #like
  def liked_by?(question_id)
    likes.where(question_id: question_id).exists?
  end
         
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :question_params, only: [:create, :destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    Like.create(user_id: current_user.id, question_id: params[:id])
  end
  
  def destroy
    Like.find_by(user_id: current_user.id, question_id: params[:id]).destroy
  end
  
  private
  
  def question_params
    @question = Question.find(params[:id])
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
  def index
    @questions = Question.all.order(created_at: :desc)
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "管理者ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "管理者新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins/show.html.slim
.boxes
  .box
    h1.box1
      = @admin.name
      
    - if @admin.avatar.attached?
      = image_tag @admin.avatar, class: "box2"
    - else
      = image_tag ("/no-profile.png"), class: "box2"
      
    = link_to "回答", admin_path(@admin.id), class: "box3-1"
    
    - if current_user || current_admin === @admin
      = link_to "プロフィール編集", edit_admin_registration_path, class: "box4"
      
  - @admin.answers.order(created_at: :desc).each do |answer|
    |  <div class="box" id="question_
    = answer.question_id
    | "> 
    = render 'top/top', question: answer.question

app/views/home/top.html.erb
<header>
  <div class="container">
    <ul class="header-list">
      <li class="header-item">
        <a href="/"><img src="/hakui.png" alt="画像がありません" ></a>
      </li>
      <li class="header-item">
        <a href="#"><p>🔎</p></a>
      </li>
      <li class="header-item">
        <a href="#"><img class="margin-top" src="/no-profile.png" alt="画像がありません" ></a>
      </li>
    </ul>
  </div>
</header>

<main>
  
</main>