config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :questions, only: [:index, :new, :show, :create, :destroy]
  resources :users, only: [:show]
  resources :admins, only: [:show]
  resources :answers, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :playlists, only: [:index]
  resources :maps, only: [:index]
  
  # search controller
  get '/search', to: 'searchs#search'
  get '/search/form', to: 'searchs#form'
  
  # like controller
  get 'likes/:id' => 'likes#show', as: 'likes'
  post 'likes/:id' => 'likes#create', as: 'create_like'
  delete 'likes/:id' => 'likes#destroy', as: 'destroy_like'
  
  root 'top#index'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :answers
  has_one_attached :avatar
  
  # update_without_current_password
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  # association
  belongs_to :question
  belongs_to :admin
  
  # validation
  validates :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :text, maximum: 200, allow_nil: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  # association
  belongs_to :question
  belongs_to :user
  
end

app/models/question.rb
class Question < ApplicationRecord

  # association
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_one :answer, dependent: :destroy
  
  # validation
  validates :title, :text, presence: { message: "入力してください" }
  validates :text, uniqueness: { case_sensitive: false, message: "すでに質問されています", allow_nil: true }
  validates_length_of :title, maximum: 20, allow_nil: true
  validates_length_of :text, maximum: 100, allow_nil: true
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # association
  has_many :questions
  has_many :likes
  has_one_attached :avatar
  
  #like
  def liked_by?(question_id)
    likes.where(question_id: question_id).exists?
  end
         
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def show
    @admin = Admin.find(params[:id])
  end
  
  protected
  def after_sign_in_path_for(resource)
    admin_items_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :question_params, only: [:create, :destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    Like.create(user_id: current_user.id, question_id: params[:id])
  end
  
  def destroy
    Like.find_by(user_id: current_user.id, question_id: params[:id]).destroy
  end
  
  private
  
  def question_params
    @question = Question.find(params[:id])
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  
  def search
    @model = params["model"]
    @text = params["text"]
    @records = search_for(@model, @text)
    if params[:text].present?
      @tracks = RSpotify::Track.search(params[:text], market: 'JP')
    end
  end
  
  def show
  end
  
  private
  def search_for(model, text)
    if model == 'user'
      User.where('nickname LIKE ?', '%'+text+'%')
    elsif model == 'question'
      Question.where('text LIKE ?', '%'+text+'%')
    end
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
  def index
    @questions = Question.all.order(created_at: :desc)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searchs/form.html.slim
.boxes
  .search-background
    h1[style="text-align: center;"]
      | 検索画面
    = form_tag(search_path, method: :get) do
      = text_field_tag 'text'
      = select_tag 'model', options_for_select({ "Question & Music" => "question", "User" => "user" })
      = submit_tag '検索'

app/views/searchs/search.html.erb
<div class="boxes">
  <% if @model == 'user' %>
    <h3>【Userの検索結果】検索ワード：<%= @text %></h3>
    <% @records.each do |record| %>
      <div class="search-background">
        <div style="display: flex">
          <% if record.avatar %>
            <%= link_to image_tag(record.avatar), user_path(record.id), class: "search-image" %>
          <% else %>
            <%= link_to image_tag("/no-profile.png"), user_path(record.id), class: "search-image" %>
          <% end %>
          <p><%= record.nickname %></p>
        </div>
      </div>
    <% end %>
  <% else @model == 'question' %>
    <h3>【Questionの検索結果】検索ワード：<%= @text %></h3>
    <% @records.each do |record| %>
      <div class="box" id="question_<%= record.id %>">
        <%= render 'top/top', question: record %>
      </div>
    <% end %>
    <h3>曲名検索結果</h3>
    <% @tracks.each do |track| %>
      <div class="box">
        <h3 class="box1"><%= track.name %></h3>
        <img src="<%= track.album.images.first["url"] %>" class="box3-1">
        <h3 class="box3-2"><%= track.artists[0].name %></h3>
        <iframe src="<%= track.preview_url %>" class="box2" style="width: 150px; height: 58px;">
      </div>
    <% end %>
  <% end %>
</div>